Prefix: "&3CombatPlus &7>>"
NoPermission: "&aYou don't have the permission do du that!"
ReforgeCommand: true
Permissions:
  Aote: 'combatplus.aote'
  Reforge: 'combatplus.reforge'
  Viewrecipe: 'combatplus.viewrecipe'